# Generated by Django 5.0.6 on 2024-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuser',
            name='twitter_image',
            field=models.ImageField(blank=True, default='', upload_to='twitter_image'),
        ),
    ]
